tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: uche_tasty_bytes_dbt_db
      schema: dev
      warehouse: uche_tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: uche_tasty_bytes_dbt_db
      schema: prod
      warehouse: uche_tasty_bytes_dbt_wh